cards_homepage:
    pattern:  /
    defaults: { _controller: CardsBundle:Home:index }
########################CRUDS CONTROLLERS#########################
_admin_tarjetas:
    resource: "@CardsBundle/Controller/CardCrudController.php"
    type:     annotation
    prefix:   /admin/tarjetas
_admin_categorias:
    resource: "@CardsBundle/Controller/CategoryCrudController.php"
    type:     annotation
    prefix:   /admin/categorias
_admin_gcategorias:
    resource: "@CardsBundle/Controller/GroupCategoryCrudController.php"
    type:     annotation
    prefix:   /admin/gruposcategorias