parameters:
#    cards.example.class: Upc\Cards\Bundle\CardsBundle\Example

services:
    cards_crud.form.type.category:
        class: Upc\Cards\Bundle\CardsBundle\Form\Type\CategoryType
        tags:
            - { name: form.type, alias: category }
    cards_crud.form.type.category_search:
        class: Upc\Cards\Bundle\CardsBundle\Form\Type\CategorySearchType
        tags:
            - { name: form.type, alias: category_search }
    cards_crud.form.type.card:
        class: Upc\Cards\Bundle\CardsBundle\Form\Type\CardType
        tags:
            - { name: form.type, alias: card }            
    cards_crud.form.type.card_search:
        class: Upc\Cards\Bundle\CardsBundle\Form\Type\CardSearchType
        tags:
            - { name: form.type, alias: card_search }
    cards_crud.form.type.group_category:
        class: Upc\Cards\Bundle\CardsBundle\Form\Type\GroupCategoryType
        tags:
            - { name: form.type, alias: group_category }
    cards_crud.form.type.gcategory_search:
        class: Upc\Cards\Bundle\CardsBundle\Form\Type\GroupCategorySearchType
        tags:
            - { name: form.type, alias: gcategory_search }