parameters:
#    security_backend.example.class: Upc\Cards\Bundle\SecurityBackendBundle\Example

services:
#    security_backend.example:
#        class: %security_backend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
