<?php

namespace Upc\Cards\Bundle\CardsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CardCategoryUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardCategoryUserRepository extends EntityRepository {

    public function getCardByUserId($user = null) {

        $status = 1;

        $qb = $this->createQueryBuilder('cu')
                ->select('cu, cr, c')
                ->innerJoin('cu.category', 'cr')
                ->innerJoin('cu.card', 'c')
                ->where('cr.status = :c_status')
                ->andWhere('cu.status = :c_status')
                ->setParameter('c_status', $status);

        return $qb->getQuery()->getArrayResult();
    }

}
