<?php

namespace Upc\Cards\Bundle\CardsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardRepository extends EntityRepository {

    public function findUsingLike($filter = array()) {
        array_walk($filter, function(&$v, &$k) {
                    if ($k === 'title') {
                        $v = " c.$k LIKE '%$v%'";
                    } else {
                        $v = "c.$k = $v";
                    }
                });
        $filter = count($filter) > 0 ? 'WHERE ' . implode(' AND ', $filter) : '';
        $query = $this->getEntityManager()
                ->createQuery('SELECT c FROM CardsBundle:Card c ' . $filter);
        return $query->getResult();
    }

}
