<?php

namespace Upc\Cards\Bundle\CardsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PerfilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerfilRepository extends EntityRepository
{
}
